name: deploy-to-k8s

on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
      service_path:
        required: true
        type: string
      production_path:
        required: true
        type: string
    secrets:
      GH_PAT:
        required: true
      KUBECONFIG:
        required: true
      GHCR_TOKEN:
        required: true
      NPM_TOKEN:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repo
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and push image
        run: |
          docker build \
            --build-arg NPM_TOKEN=${{ secrets.NPM_TOKEN }} \
            -t ${{ inputs.image_name }}:${{ github.sha }} .
          docker push ${{ inputs.image_name }}:${{ github.sha }}

      - name: Checkout infrastructure repo
        uses: actions/checkout@v4
        with:
          repository: study-words/infrastructure
          token: ${{ secrets.GH_PAT }}
          path: infrastructure

      - name: Set image tag
        run: |
          kustomize edit set image "${{ inputs.image_name }}=${{ inputs.image_name }}:${{ github.sha }}"
        working-directory: infrastructure/${{ inputs.service_path }}

      - name: Setup kubeconfig
        run: echo "${{ secrets.KUBECONFIG }}" > kubeconfig.yaml

      - name: Deploy
        env:
          KUBECONFIG: ${{ github.workspace }}/kubeconfig.yaml
        run: |
          kubectl apply -k infrastructure/${{ inputs.production_path }}

      - name: Wait for deployment rollout
        run: kubectl rollout status deployment/user -n core --timeout=60s

